jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Build the Project
        run: mvn clean install -DskipTests

      - name: Coverage per Test Execution
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test

      - name: Verify target folder existence
        run: |
          if [ ! -d "${{ github.workspace }}/target/surefire-reports" ]; then
            echo "Directory target/surefire-reports does not exist. Creating it."
            mkdir -p ${{ github.workspace }}/target/surefire-reports
          fi

      - name: Upload target folder
        uses: actions/upload-pages-artifact@v3
        with:
          name: target
          path: |
            ${{ github.workspace }}/target/surefire-reports

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: target/surefire-reports/TEST-TestSuite.xml
          reporter: java-junit
          java-version: 21